[package]
name = "aoc-2019-11"
version = "0.1.0"
authors = ["Raphael Nestler <raphael.nestler@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intcode-computer = { "path" = "../intcode-computer" }
